#!/usr/bin/env perl
# Generate delta.dat for flat bands. The same mesh is used as for spectral functions.
# Rok Zitko, rok.zitko@ijs.si, June 2012

use warnings;
use strict;

my $max = `getparam broaden_max param.loop`;
my $ratio = `getparam broaden_ratio param.loop`;
my $min = `getparam broaden_min param.loop`;
chomp ($max, $ratio, $min);

my $Gamma = `getparam Gamma param.loop`;
chomp($Gamma);

my @l = ();
for (my $x = $max; $x >= $min; $x /= $ratio) {
    my $xpos = $x;
    my $ypos = initialfn($xpos);
    my $xneg = -$x;
    my $yneg = initialfn($xneg);
    push(@l, [$xpos, $ypos]);
    push(@l, [$xneg, $yneg]);
}

my @sorted = sort { $a->[0] <=> $b->[0] } @l;

my $fn = "Delta.dat";
open(OUT, ">$fn") or die "Can't open $fn: $!. Stopped";
foreach (@sorted) {
    my ($x, $y) = @$_;
    print OUT "$x $y\n";
}
close(OUT);

# Hybridisation function
system "kk Delta.dat Delta-re.dat";

sub initialfn 
{
    my $x = shift;
    my $g = (abs($x) < 1.0 ? $Gamma : 0);
    return $g;
}
